#!/usr/bin/env bash
set -euo pipefail

COMMIT=$(git rev-parse --short=8 HEAD)
DIRTY=$(git diff --shortstat) && [[ -n $DIRTY ]] && COMMIT="$COMMIT.mod"
STAMP=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
PLATFORM="$(uname -s).$(go env GOARCH)"

OUT="internal/buildinfo/build.go"
mkdir -p "$(dirname "$OUT")"

cat > "$OUT" <<EOF
// Code‑generated by buildinfo.sh — DO NOT EDIT.
package buildinfo
var (
    Commit    = "$COMMIT"
    Timestamp = "$STAMP"
    Platform  = "$PLATFORM"
)
EOF
echo "✅ Generated $OUT"
